#!/usr/bin/env node
// Regenerates src/generated/* from the real forge and anchor build artifacts, so the
// published ABI and IDL can never drift from the contracts they describe.
//
//   node scripts/generate.mjs           write the files
//   node scripts/generate.mjs --check   fail if they are stale (used in CI and prepublish)
//
// Requires `forge build` (evm/) and `anchor build` (solana/) to have run first.

import {readFileSync, writeFileSync, existsSync} from "node:fs";
import {dirname, resolve} from "node:path";
import {fileURLToPath} from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const repo = resolve(here, "..", "..");
const check = process.argv.includes("--check");

const FORGE = resolve(repo, "evm/out/Deliver.sol/Deliver.json");
const IDL = resolve(repo, "solana/target/idl/deliver.json");

// In --check mode a missing artifact means that half was not built in this job (CI runs the
// EVM and Solana checks separately), so skip it rather than failing. In write mode it is fatal.
function need(path, how) {
  if (!existsSync(path)) {
    if (check) {
      console.log(`skipping ${path} — not built in this job`);
      return null;
    }
    console.error(`missing artifact: ${path}\n  run \`${how}\` first`);
    process.exit(1);
  }
  return JSON.parse(readFileSync(path, "utf8"));
}

const banner = "// GENERATED by scripts/generate.mjs — do not edit by hand.\n" +
  "// Source of truth is the contract build output; run `npm run generate` after changing a contract.\n\n";

const forge = need(FORGE, "cd evm && forge build");
const idl = need(IDL, "cd solana && anchor build");

const files = {};
if (forge) files["src/generated/abi.ts"] =
    banner +
    "/** ABI of `evm/src/Deliver.sol`, straight from the Foundry build output. */\n" +
    `export const deliverAbi = ${JSON.stringify(forge.abi, null, 2)} as const;\n\n` +
    "export type DeliverAbi = typeof deliverAbi;\n";

if (idl) files["src/generated/idl.ts"] =
    banner +
    "/** Anchor IDL of `solana/programs/deliver`, straight from the anchor build output. */\n" +
    `export const deliverIdl = ${JSON.stringify(idl, null, 2)} as const;\n\n` +
    "export type DeliverIdl = typeof deliverIdl;\n\n" +
    "/** Program id the IDL was built with. Override it if you deploy your own instance. */\n" +
    `export const DELIVER_PROGRAM_ID = ${JSON.stringify(idl.address)} as const;\n`;

let stale = false;
for (const [rel, content] of Object.entries(files)) {
  const path = resolve(here, "..", rel);
  const current = existsSync(path) ? readFileSync(path, "utf8") : null;
  if (current === content) continue;
  if (check) {
    console.error(`STALE: ${rel} does not match the current build artifacts`);
    stale = true;
  } else {
    writeFileSync(path, content);
    console.log(`wrote ${rel}`);
  }
}

if (check) {
  if (stale) {
    console.error("\nrun `npm run generate` and commit the result");
    process.exit(1);
  }
  console.log("generated files are up to date");
}
